### ISSUE TITLE
Missing book code

### ISSUE THREAD

**Issue by martinduo** [dirkstrauss/ApressVS2019#1]
This repo does not match the code shown in the book and makes following chapter 1 difficult. I cannot create the results shown in the figures.

**Comment by dirkstrauss** [comment]
There are only 2 code listings for chapter 1. All the rest are figures. These figures illustrate features of Visual Studio such as Reference Highlighting, Go To Definition, Multi-caret Editing and so on. The figures are therefore applicable to any code, and not specific to the code in the book.
